[package]
name = "html2text"
version = "0.2.1"
authors = ["Chris Emerson <github@mail.nosreme.org>"]
description = "Render HTML as plain text."
repository = "https://github.com/jugglerchris/rust-html2text/"
readme = "README.md"
documentation = "https://docs.rs/html2text/"
edition = "2018"

keywords = ["html", "text"]
license = "MIT"

[badges]
travis-ci = { repository = "jugglerchris/rust-html2text" }
appveyor = { repository = "jugglerchris/rust-html2text", service = "github" }

[dependencies]
clippy = { version = "0.0.302", optional=true }
html5ever = "0.25.0"
unicode-width = "0.1.5"
backtrace = { version = "0.3", optional=true }
markup5ever_rcdom = "0.1.0"

[features]
html_trace = []
html_trace_bt = ["backtrace"]
default = []

[[example]]
name = "html2term"
path = "examples/html2term.rs"

[[example]]
name = "html2text"
path = "examples/html2text.rs"

[dev-dependencies]
argparse = "0.2.2"

[target.'cfg(unix)'.dev-dependencies]
termion = "1.5"
